"""News Search RSS Feed Registry

This module contains all RSS feed URLs for news-search categories.
Just add more URLs to any category and they will automatically be detected and used.

Categories cover general/world news plus lifestyle, entertainment, sports, and
consumer-tech topics curated from the "Recommended Categories" section of
plenaryapp/awesome-rss-feeds (country-specific national news sources were
intentionally excluded — see web_search_feed.py for developer/engineering-focused
feeds such as Programming, Web Development, UI/UX, and mobile dev blogs).

Categories:
- all: General technology news (+ general "Tech" gadget/review feeds)
- news: General world/breaking news
- business: Business, finance, and economy
- startups: Startup ecosystem, funding, and founder-focused publications
- venture: Venture capital news
- ai: Artificial intelligence and machine learning
- space: Space exploration and astronomy
- apps: Mobile and desktop apps
- security: Cybersecurity and privacy
- enterprise: Enterprise IT
- fintech: Financial technology
- transportation: Transportation and mobility
- robotics: Robotics industry
- hardware: Computer and consumer hardware
- mobile: Mobile devices — Android and Apple/iOS news and rumors
- gaming: Video game news, reviews, and gaming communities
- cloud: Cloud computing and infrastructure
- cryptocurrency: Crypto and blockchain
- climate: Climate and environment
- social: Social media platforms
- commerce: E-commerce
- open_source: Open source software
- sports: General sports news
- football: (Soccer) football news
- cricket: Cricket news, commentary, and podcasts
- tennis: Tennis news and match coverage
- movies: Film news, reviews, and industry publications
- television: TV show news, reviews, and recap sites
- music: Music news, charts, and genre publications
- fashion: Fashion news, style blogs, and magazines
- beauty: Beauty, skincare, and cosmetics
- food: Food blogs, recipe sites, and cooking channels
- travel: Travel blogs, guides, and destination news
- cars: Automotive news, reviews, and enthusiast blogs
- architecture: Architecture and building-design publications
- books: Book review sites, reading blogs, and literary communities
- interior_design: Interior design and home decor blogs and magazines
- diy: Do-it-yourself, home improvement, and maker blogs
- funny: Comedy, comics, and humor sites
- history: History podcasts, blogs, and museum feeds
- personal_finance: Personal finance, budgeting, and money-management blogs
- photography: Photography tips, galleries, and gear-focused blogs
- science: Science news, journals, and popular-science podcasts (media outlets,
  not research papers — see web_search_feed.py's "research" category for arXiv
  and academic-paper feeds)
- And more...
"""

from typing import Any, Dict, List

TECHCRUNCH_FEEDS: Dict[str, List[Dict[str, Any]]] = {
    "all": [
        {"url": "https://techcrunch.com/feed/", "verified": False, "notes": "TechCrunch main technology news feed."},
        {"url": "https://www.theverge.com/rss/index.xml", "verified": False, "notes": "The Verge technology and innovation news."},
        {"url": "https://feeds.arstechnica.com/arstechnica/index", "verified": False, "notes": "Ars Technica technology journalism."},
        {"url": "https://www.wired.com/feed/rss", "verified": False, "notes": "WIRED technology and science news."},
        {"url": "https://www.zdnet.com/news/rss.xml", "verified": False, "notes": "ZDNet enterprise and technology news."},
        {"url": "https://venturebeat.com/feed/", "verified": False, "notes": "Technology and startup news."},
        {"url": "https://www.technologyreview.com/feed/", "verified": False, "notes": "MIT Technology Review news."},
        {"url": "https://www.engadget.com/rss.xml", "verified": False, "notes": "Consumer technology and gadget news."},
        {"url": "https://www.cnet.com/rss/news/", "verified": False, "notes": "Technology news and reviews."},
        {"url": "https://www.techmeme.com/feed.xml", "verified": False, "notes": "Aggregated top technology stories."},
        {"url": "https://thenextweb.com/feed/", "verified": False, "notes": "Technology and startup news."},
        {"url": "https://atp.fm/rss", "verified": False, "notes": "Accidental Tech Podcast"},
        {"url": "https://www.relay.fm/analogue/feed", "verified": False, "notes": "Analog(ue)"},
        {"url": "http://feeds.arstechnica.com/arstechnica/index", "verified": False, "notes": "Ars Technica"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=CNETTV", "verified": False, "notes": "CNET"},
        {"url": "https://www.relay.fm/clockwise/feed", "verified": False, "notes": "Clockwise"},
        {"url": "https://gizmodo.com/rss", "verified": False, "notes": "Gizmodo"},
        {"url": "https://news.ycombinator.com/rss", "verified": False, "notes": "Hacker News"},
        {"url": "https://lifehacker.com/rss", "verified": False, "notes": "Lifehacker"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=LinusTechTips", "verified": False, "notes": "Linus Tech Tips"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=marquesbrownlee", "verified": False, "notes": "Marques Brownlee"},
        {"url": "http://feeds.mashable.com/Mashable", "verified": False, "notes": "Mashable"},
        {"url": "https://readwrite.com/feed/", "verified": False, "notes": "ReadWrite"},
        {"url": "https://feeds.megaphone.fm/replyall", "verified": False, "notes": "Reply All"},
        {"url": "https://www.relay.fm/rocket/feed", "verified": False, "notes": "Rocket"},
        {"url": "http://rss.slashdot.org/Slashdot/slashdotMain", "verified": False, "notes": "Slashdot"},
        {"url": "http://stratechery.com/feed/", "verified": False, "notes": "Stratechery by Ben Thompson"},
        {"url": "http://feeds.feedburner.com/TechCrunch", "verified": False, "notes": "TechCrunch"},
        {"url": "https://www.blog.google/rss/", "verified": False, "notes": "The Keyword"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=TheVerge", "verified": False, "notes": "The Verge"},
        {"url": "https://feeds.megaphone.fm/vergecast", "verified": False, "notes": "The Vergecast"},
        {"url": "https://feeds.twit.tv/twit.xml", "verified": False, "notes": "This Week in Tech (Audio)"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=unboxtherapy", "verified": False, "notes": "Unbox Therapy"},
    ],
    "news": [
        {"url": "http://feeds.bbci.co.uk/news/world/rss.xml", "verified": False, "notes": "BBC News - World"},
        {"url": "http://rss.cnn.com/rss/edition_world.rss", "verified": False, "notes": "CNN.com - RSS Channel - World"},
        {"url": "https://www.cnbc.com/id/100727362/device/rss/rss.html", "verified": False, "notes": "International: Top News And Analysis"},
        {"url": "http://feeds.feedburner.com/ndtvnews-world-news", "verified": False, "notes": "NDTV News - World-news"},
        {"url": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", "verified": False, "notes": "NYT > World News"},
        {"url": "https://news.google.com/rss", "verified": False, "notes": "Top stories - Google News"},
        {"url": "http://feeds.washingtonpost.com/rss/world", "verified": False, "notes": "World"},
        {"url": "https://www.reddit.com/r/worldnews/.rss", "verified": False, "notes": "World News"},
        {"url": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", "verified": False, "notes": "World News Headlines - Times of India"},
        {"url": "https://www.theguardian.com/world/rss", "verified": False, "notes": "World news - The Guardian"},
        {"url": "https://www.yahoo.com/news/rss", "verified": False, "notes": "Yahoo News - Latest News & Headlines"},
    ],
    "business": [
        {"url": "https://techcrunch.com/category/business/feed/", "verified": True, "notes": "TechCrunch business category feed."},
        {"url": "https://www.ft.com/technology?format=rss", "verified": False, "notes": "Financial Times technology RSS pattern; verify in your environment."},
        {"url": "https://feeds.a.dj.com/rss/RSSWSJD.xml", "verified": False, "notes": "WSJ tech feed pattern; verify in your environment."},
        {"url": "https://www.reuters.com/technology/", "verified": False, "notes": "Reuters technology section."},
        {"url": "https://www.bloomberg.com/technology", "verified": False, "notes": "Bloomberg technology section; RSS availability may vary."},
        {"url": "https://www.investing.com/rss/news.rss", "verified": False, "notes": "All News"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=Bloomberg", "verified": False, "notes": "Bloomberg Quicktake"},
        {"url": "https://seekingalpha.com/market_currents.xml", "verified": False, "notes": "Breaking News on Seeking Alpha"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=businessinsider", "verified": False, "notes": "Business Insider"},
        {"url": "https://ducttape.libsyn.com/rss", "verified": False, "notes": "Duct Tape Marketing"},
        {"url": "https://economictimes.indiatimes.com/rssfeedsdefault.cms", "verified": False, "notes": "Economic Times"},
        {"url": "https://www.forbes.com/business/feed/", "verified": False, "notes": "Forbes - Business"},
        {"url": "https://fortune.com/feed", "verified": False, "notes": "Fortune"},
        {"url": "http://feeds.harvardbusiness.org/harvardbusiness/ideacast", "verified": False, "notes": "HBR IdeaCast"},
        {"url": "https://www.business-standard.com/rss/home_page_top_stories.rss", "verified": False, "notes": "Home Page"},
        {"url": "https://feeds.npr.org/510313/podcast.xml", "verified": False, "notes": "How I Built This with Guy Raz"},
        {"url": "https://feeds.feedburner.com/Mixergy-main-podcast", "verified": False, "notes": "Startup Stories - Mixergy"},
        {"url": "https://tim.blog/feed/", "verified": False, "notes": "The Blog of Author Tim Ferriss"},
        {"url": "http://thegrowthshow.hubspot.libsynpro.com/", "verified": False, "notes": "The Growth Show"},
        {"url": "https://www.cnbc.com/id/100003114/device/rss/rss.html", "verified": False, "notes": "US Top News and Analysis"},
        {"url": "https://finance.yahoo.com/news/rssindex", "verified": False, "notes": "Yahoo Finance"},
    ],
    "startups": [
        {"url": "https://techcrunch.com/category/startups/feed/", "verified": False, "notes": "Startup ecosystem news."},
        {"url": "https://venturebeat.com/feed/", "verified": False, "notes": "Startup and venture news."},
        {"url": "https://www.geekwire.com/feed/", "verified": False, "notes": "Startup and innovation reporting."},
        {"url": "https://thenextweb.com/feed/", "verified": False, "notes": "Startup industry coverage."},
        {"url": "https://news.crunchbase.com/feed/", "verified": False, "notes": "Funding and startup news."},
        {"url": "https://avc.com/feed/", "verified": False, "notes": "AVC"},
        {"url": "https://bothsidesofthetable.com/feed", "verified": False, "notes": "Both Sides of the Table - Medium"},
        {"url": "http://feeds.feedburner.com/entrepreneur/latest", "verified": False, "notes": "Entrepreneur"},
        {"url": "https://feld.com/feed", "verified": False, "notes": "Feld Thoughts"},
        {"url": "https://www.forbes.com/entrepreneurs/feed/", "verified": False, "notes": "Forbes - Entrepreneurs"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=GaryVaynerchuk", "verified": False, "notes": "GaryVee"},
        {"url": "https://hnrss.org/frontpage", "verified": False, "notes": "Hacker News: Front Page"},
        {"url": "https://www.inc.com/rss/", "verified": False, "notes": "Inc.com"},
        {"url": "https://www.intercom.com/blog/feed", "verified": False, "notes": "Inside Intercom"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=marieforleo", "verified": False, "notes": "Marie Forleo"},
        {"url": "https://rss.art19.com/masters-of-scale", "verified": False, "notes": "Masters of Scale with Reid Hoffman"},
        {"url": "http://www.aaronsw.com/2002/feeds/pgessays.rss", "verified": False, "notes": "Paul Graham: Essays"},
        {"url": "https://www.producthunt.com/feed", "verified": False, "notes": "Product Hunt — The best new products, every day"},
        {"url": "https://www.quicksprout.com/rss", "verified": False, "notes": "Quick Sprout"},
        {"url": "https://feeds2.feedburner.com/SmallBusinessTrends", "verified": False, "notes": "Small Business Trends"},
        {"url": "http://feeds.feedburner.com/smartpassiveincome", "verified": False, "notes": "Smart Passive Income"},
        {"url": "https://www.springwise.com/feed", "verified": False, "notes": "Springwise"},
        {"url": "https://steveblank.com/feed/", "verified": False, "notes": "Steve Blank"},
        {"url": "https://startupjunkie.libsyn.com/rss", "verified": False, "notes": "The Startup Junkies Podcast"},
        {"url": "https://rss.art19.com/tim-ferriss-show", "verified": False, "notes": "The Tim Ferriss Show"},
        {"url": "http://feeds.feedburner.com/twistvid", "verified": False, "notes": "This Week in Startups - Video"},
        {"url": "https://feeds.feedburner.com/venturebeat/SZYF", "verified": False, "notes": "VentureBeat"},
        {"url": "https://feld.com/archives/tag/blog/feed", "verified": False, "notes": "blog – Feld Thoughts"},
    ],
    "venture": [
        {"url": "https://techcrunch.com/category/venture/feed/", "verified": True, "notes": "TechCrunch venture category feed."},
        {"url": "https://techcrunch.com/tag/venture/feed/", "verified": True, "notes": "TechCrunch venture tag feed."},
        {"url": "https://venturebeat.com/feed/", "verified": True, "notes": "VentureBeat covers startups and venture."},
    ],
    "ai": [
        {"url": "https://techcrunch.com/category/artificial-intelligence/feed/", "verified": True, "notes": "TechCrunch AI category feed."},
        {"url": "https://techcrunch.com/tag/artificial-intelligence/feed/", "verified": True, "notes": "TechCrunch AI tag feed."},
        {"url": "https://www.technologyreview.com/topic/artificial-intelligence/feed/", "verified": True, "notes": "MIT Technology Review AI topic feed."},
        {"url": "https://tldr.tech/api/rss/ai", "verified": True, "notes": "TLDR AI feed."},
        {"url": "https://importai.substack.com/feed", "verified": True, "notes": "Import AI newsletter feed."},
        {"url": "https://simonwillison.net/atom/everything/", "verified": True, "notes": "Simon Willison Atom feed; often covers AI/tools."},
        {"url": "https://marktechpost.com/feed/", "verified": False, "notes": "MarkTechPost feed; verify in your environment."},
        {"url": "https://www.artificialintelligence-news.com/feed/", "verified": False, "notes": "AI news feed pattern; verify in your environment."},
    ],
    "space": [
        {"url": "https://techcrunch.com/category/space/feed/", "verified": False, "notes": "Space technology news."},
        {"url": "https://spacenews.com/feed/", "verified": False, "notes": "Space industry reporting."},
        {"url": "https://www.space.com/feeds/all", "verified": False, "notes": "Space exploration news."},
        {"url": "https://www.reddit.com/r/space/.rss?format=xml", "verified": False, "notes": "/r/space: news, articles and discussion"},
        {"url": "https://www.nasa.gov/rss/dyn/breaking_news.rss", "verified": False, "notes": "NASA Breaking News"},
        {"url": "https://www.newscientist.com/subject/space/feed/", "verified": False, "notes": "New Scientist - Space"},
        {"url": "https://www.skyandtelescope.com/feed/", "verified": False, "notes": "Sky & Telescope"},
        {"url": "https://www.theguardian.com/science/space/rss", "verified": False, "notes": "Space - The Guardian"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=spacexchannel", "verified": False, "notes": "SpaceX"},
    ],
    "apps": [
        {"url": "https://techcrunch.com/category/apps/feed/", "verified": True, "notes": "TechCrunch apps category feed."},
        {"url": "https://www.androidauthority.com/feed/", "verified": True, "notes": "Android Authority main feed."},
        {"url": "https://www.theverge.com/apps/rss/index.xml", "verified": True, "notes": "The Verge apps feed."},
    ],
    "security": [
        {"url": "https://techcrunch.com/category/security/feed/", "verified": True, "notes": "TechCrunch security category feed."},
        {"url": "https://www.bleepingcomputer.com/feed/", "verified": True, "notes": "BleepingComputer main feed."},
        {"url": "https://krebsonsecurity.com/feed/", "verified": True, "notes": "Krebs on Security feed."},
        {"url": "https://www.schneier.com/feed/atom/", "verified": True, "notes": "Bruce Schneier Atom feed."},
        {"url": "https://www.darkreading.com/rss.xml", "verified": False, "notes": "Dark Reading feed pattern; verify in your environment."},
        {"url": "https://thehackernews.com/feeds/posts/default", "verified": False, "notes": "The Hacker News Atom feed pattern; verify in your environment."},
    ],
    "enterprise": [
        {"url": "https://techcrunch.com/category/enterprise/feed/", "verified": True, "notes": "TechCrunch enterprise category feed."},
        {"url": "https://www.cio.com/feed/", "verified": False, "notes": "CIO feed pattern; verify in your environment."},
        {"url": "https://www.computerworld.com/index.rss", "verified": False, "notes": "Computerworld feed pattern; verify in your environment."},
        {"url": "https://www.networkworld.com/feed/", "verified": False, "notes": "Network World feed pattern; verify in your environment."},
        {"url": "https://www.zdnet.com/topic/enterprise/rss.xml", "verified": False, "notes": "ZDNET enterprise topic feed pattern; verify in your environment."},
    ],
    "fintech": [
        {"url": "https://techcrunch.com/category/fintech/feed/", "verified": True, "notes": "TechCrunch fintech category feed."},
    ],
    "transportation": [
        {"url": "https://techcrunch.com/category/transportation/feed/", "verified": True, "notes": "TechCrunch transportation category feed."},
    ],
    "robotics": [
        {"url": "https://techcrunch.com/category/robotics/feed/", "verified": False, "notes": "Robotics industry news."},
        {"url": "https://www.roboticsbusinessreview.com/feed/", "verified": False, "notes": "Robotics business coverage."},
    ],
    "hardware": [
        {"url": "https://techcrunch.com/category/hardware/feed/", "verified": True, "notes": "TechCrunch hardware category feed."},
        {"url": "https://www.tomshardware.com/feeds.xml", "verified": False, "notes": "Tom's Hardware feed pattern; verify in your environment."},
        {"url": "https://www.anandtech.com/rss/", "verified": True, "notes": "AnandTech RSS feed."},
        {"url": "https://www.servethehome.com/feed/", "verified": True, "notes": "ServeTheHome feed."},
    ],
    "mobile": [
        {"url": "https://techcrunch.com/category/mobile/feed/", "verified": True, "notes": "TechCrunch mobile category feed."},
        {"url": "https://9to5mac.com/feed", "verified": True, "notes": "9to5Mac main feed."},
        {"url": "https://9to5google.com/feed/", "verified": True, "notes": "9to5Google main feed."},
        {"url": "https://www.androidpolice.com/feed/", "verified": True, "notes": "Android Police main feed."},
        {"url": "https://feeds.twit.tv/aaa.xml", "verified": False, "notes": "All About Android (Audio)"},
        {"url": "https://blog.google/products/android/rss", "verified": False, "notes": "Android"},
        {"url": "https://www.reddit.com/r/android/.rss", "verified": False, "notes": "Android"},
        {"url": "https://www.androidauthority.com/feed", "verified": False, "notes": "Android Authority"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=AndroidAuthority", "verified": False, "notes": "Android Authority"},
        {"url": "https://androidauthority.libsyn.com/rss", "verified": False, "notes": "Android Authority Podcast"},
        {"url": "http://feeds.androidcentral.com/androidcentral", "verified": False, "notes": "Android Central - Android Forums, News, Reviews, Help and Android Wallpapers"},
        {"url": "http://feeds.feedburner.com/AndroidCentralPodcast", "verified": False, "notes": "Android Central Podcast"},
        {"url": "https://androidcommunity.com/feed/", "verified": False, "notes": "Android Community"},
        {"url": "http://feeds.feedburner.com/AndroidPolice", "verified": False, "notes": "Android Police – Android news, reviews, apps, games, phones, tablets"},
        {"url": "https://www.androidguys.com/feed", "verified": False, "notes": "AndroidGuys"},
        {"url": "https://www.cultofandroid.com/feed", "verified": False, "notes": "Cult of Android"},
        {"url": "https://www.cyanogenmods.org/feed", "verified": False, "notes": "Cyanogen Mods"},
        {"url": "https://www.droid-life.com/feed", "verified": False, "notes": "Droid Life"},
        {"url": "https://www.gsmarena.com/rss-news-reviews.php3", "verified": False, "notes": "GSMArena.com - Latest articles"},
        {"url": "http://feeds2.feedburner.com/AndroidPhoneFans", "verified": False, "notes": "Phandroid"},
        {"url": "http://feeds.feedburner.com/AndroidNewsGoogleAndroidForums", "verified": False, "notes": "TalkAndroid"},
        {"url": "https://data.xda-developers.com/portal-feed", "verified": False, "notes": "xda-developers"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=Apple", "verified": False, "notes": "Apple"},
        {"url": "https://www.apple.com/newsroom/rss-feed.rss", "verified": False, "notes": "Apple Newsroom"},
        {"url": "https://appleinsider.com/rss/news/", "verified": False, "notes": "AppleInsider News"},
        {"url": "https://www.cultofmac.com/feed", "verified": False, "notes": "Cult of Mac"},
        {"url": "https://daringfireball.net/feeds/main", "verified": False, "notes": "Daring Fireball"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=macrumors", "verified": False, "notes": "MacRumors"},
        {"url": "http://feeds.macrumors.com/MacRumors-Mac", "verified": False, "notes": "MacRumors: Mac News and Rumors - Mac Blog"},
        {"url": "https://www.macstories.net/feed", "verified": False, "notes": "MacStories"},
        {"url": "https://www.macworld.com/index.rss", "verified": False, "notes": "Macworld.com"},
        {"url": "https://marco.org/rss", "verified": False, "notes": "Marco.org"},
        {"url": "http://feeds.feedburner.com/osxdaily", "verified": False, "notes": "OS X Daily"},
        {"url": "https://www.loopinsight.com/feed", "verified": False, "notes": "The Loop"},
        {"url": "https://www.reddit.com/r/apple/.rss", "verified": False, "notes": "The unofficial Apple community"},
        {"url": "https://www.reddit.com/r/iphone/.rss", "verified": False, "notes": "r/iPhone"},
    ],
    "gaming": [
        {"url": "https://techcrunch.com/category/gaming/feed/", "verified": True, "notes": "TechCrunch gaming category feed."},
        {"url": "https://www.theverge.com/gaming/rss/index.xml", "verified": True, "notes": "The Verge gaming feed."},
        {"url": "https://kotaku.com/rss", "verified": True, "notes": "Kotaku RSS feed."},
        {"url": "https://www.pcgamer.com/rss/", "verified": True, "notes": "PC Gamer RSS feed pattern."},
        {"url": "https://www.escapistmagazine.com/v2/feed/", "verified": False, "notes": "Escapist Magazine"},
        {"url": "https://www.eurogamer.net/?format=rss", "verified": False, "notes": "Eurogamer.net"},
        {"url": "http://feeds.feedburner.com/GamasutraNews", "verified": False, "notes": "Gamasutra News"},
        {"url": "https://www.gamespot.com/feeds/mashup/", "verified": False, "notes": "GameSpot - All Content"},
        {"url": "http://feeds.ign.com/ign/all", "verified": False, "notes": "IGN All"},
        {"url": "https://indiegamesplus.com/feed", "verified": False, "notes": "Indie Games Plus"},
        {"url": "http://feeds.feedburner.com/psblog", "verified": False, "notes": "PlayStation.Blog"},
        {"url": "https://www.polygon.com/rss/index.xml", "verified": False, "notes": "Polygon -  All"},
        {"url": "http://feeds.feedburner.com/RockPaperShotgun", "verified": False, "notes": "Rock, Paper, Shotgun"},
        {"url": "https://store.steampowered.com/feeds/news.xml", "verified": False, "notes": "Steam RSS News Feed"},
        {"url": "http://feeds.feedburner.com/TheAncientGamingNoob", "verified": False, "notes": "The Ancient Gaming Noob"},
        {"url": "https://toucharcade.com/community/forums/-/index.rss", "verified": False, "notes": "TouchArcade - iPhone, iPad, Android Games Forum"},
        {"url": "https://majornelson.com/feed/", "verified": False, "notes": "Xbox's Major Nelson"},
        {"url": "https://www.reddit.com/r/gaming.rss", "verified": False, "notes": "r/gaming"},
    ],
    "cloud": [
        {"url": "https://techcrunch.com/category/cloud/feed/", "verified": True, "notes": "TechCrunch cloud category feed."},
        {"url": "https://www.cshub.com/rss/categories/cloud", "verified": False, "notes": "Cloud security feed; useful for cloud/security overlap."},
    ],
    "cryptocurrency": [
        {"url": "https://techcrunch.com/category/cryptocurrency/feed/", "verified": True, "notes": "TechCrunch crypto category feed."},
        {"url": "https://techcrunch.com/tag/cryptocurrency/feed/", "verified": True, "notes": "TechCrunch crypto tag feed."},
        {"url": "https://www.coindesk.com/arc/outboundfeeds/rss/", "verified": False, "notes": "CoinDesk RSS pattern; verify in your environment."},
        {"url": "https://cointelegraph.com/rss", "verified": True, "notes": "Cointelegraph RSS feed."},
    ],
    "climate": [
        {"url": "https://techcrunch.com/category/climate/feed/", "verified": True, "notes": "TechCrunch climate category feed."},
    ],
    "social": [
        {"url": "https://techcrunch.com/category/social/feed/", "verified": True, "notes": "TechCrunch social category feed."},
        {"url": "https://www.socialmediatoday.com/feeds/news", "verified": False, "notes": "Social Media Today feed pattern; verify in your environment."},
        {"url": "https://mashable.com/feed/", "verified": False, "notes": "Mashable feed pattern; verify in your environment."},
    ],
    "commerce": [
        {"url": "https://techcrunch.com/category/commerce/feed/", "verified": True, "notes": "TechCrunch commerce category feed."},
    ],
    "open_source": [
        {"url": "https://opensource.com/feed", "verified": False, "notes": "Open source industry news."},
        {"url": "https://www.linux.com/feed/", "verified": False, "notes": "Linux and open-source news."},
        {"url": "https://lwn.net/headlines/rss", "verified": False, "notes": "Linux and kernel news."},
    ],
    "sports": [
        {"url": "http://feeds.bbci.co.uk/sport/rss.xml", "verified": False, "notes": "BBC Sport - Sport"},
        {"url": "https://www.reddit.com/r/sports.rss", "verified": False, "notes": "Reddit Sports"},
        {"url": "http://feeds.skynews.com/feeds/rss/sports.xml", "verified": False, "notes": "Sports News - Sky News"},
        {"url": "https://www.sportskeeda.com/feed", "verified": False, "notes": "Sportskeeda"},
        {"url": "https://sports.yahoo.com/rss/", "verified": False, "notes": "Yahoo! Sports"},
        {"url": "https://www.espn.com/espn/rss/news", "verified": False, "notes": "www.espn.com - TOP"},
    ],
    "football": [
        {"url": "https://www.reddit.com/r/Championship/.rss?format=xml", "verified": False, "notes": "EFL Championship"},
        {"url": "https://www.reddit.com/r/football/.rss?format=xml", "verified": False, "notes": "Football - The People's Sport"},
        {"url": "https://www.goal.com/feeds/en/news", "verified": False, "notes": "Goal.com"},
        {"url": "https://www.football365.com/feed", "verified": False, "notes": "Football365"},
        {"url": "https://www.soccernews.com/feed", "verified": False, "notes": "Soccer News"},
    ],
    "cricket": [
        {"url": "http://feeds.bbci.co.uk/sport/cricket/rss.xml", "verified": False, "notes": "BBC Sport - Cricket"},
        {"url": "http://www.espncricinfo.com/rss/content/story/feeds/0.xml", "verified": False, "notes": "Cricket news from ESPN Cricinfo.com"},
        {"url": "https://www.theguardian.com/sport/cricket/rss", "verified": False, "notes": "Cricket - The Guardian"},
        {"url": "https://www.theroar.com.au/cricket/feed/", "verified": False, "notes": "Cricket – The Roar"},
        {"url": "http://feeds.feedburner.com/ndtvsports-cricket", "verified": False, "notes": "NDTV Sports - Cricket"},
        {"url": "https://www.wisden.com/feed", "verified": False, "notes": "Wisden"},
        {"url": "http://feeds.feedburner.com/cantbowlcantthrow", "verified": False, "notes": "Can't Bowl Can't Throw Cricket Show"},
        {"url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCSRQXk5yErn4e14vN76upOw", "verified": False, "notes": "Cricbuzz"},
        {"url": "https://www.reddit.com/r/Cricket/.rss", "verified": False, "notes": "Cricket"},
        {"url": "https://rss.acast.com/cricket-unfiltered", "verified": False, "notes": "Cricket Unfiltered"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=ecbcricket", "verified": False, "notes": "England & Wales Cricket Board"},
        {"url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCiWrjBhlICf_L_RK5y6Vrxw", "verified": False, "notes": "Pakistan Cricket"},
        {"url": "https://www.spreaker.com/show/3387348/episodes/feed", "verified": False, "notes": "Sky Sports Cricket Podcast"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=TheOfficialSLC", "verified": False, "notes": "Sri Lanka Cricket"},
        {"url": "https://podcasts.files.bbci.co.uk/p02gsrmh.rss", "verified": False, "notes": "Stumped"},
        {"url": "https://feeds.megaphone.fm/ESP9247246951", "verified": False, "notes": "Switch Hit Podcast"},
        {"url": "https://podcasts.files.bbci.co.uk/p02pcb4w.rss", "verified": False, "notes": "Tailenders"},
        {"url": "https://podcasts.files.bbci.co.uk/p02nrsl2.rss", "verified": False, "notes": "Test Match Special"},
        {"url": "http://rss.acast.com/theanalystinsidecricket", "verified": False, "notes": "The Analyst Inside Cricket"},
        {"url": "https://rss.whooshkaa.com/rss/podcast/id/1308", "verified": False, "notes": "The Grade Cricketer"},
        {"url": "http://feeds.soundcloud.com/users/soundcloud:users:341034518/sounds.rss", "verified": False, "notes": "Wisden Cricket Weekly"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=cricketaustraliatv", "verified": False, "notes": "cricket.com.au"},
    ],
    "tennis": [
        {"url": "http://feeds.bbci.co.uk/sport/tennis/rss.xml", "verified": False, "notes": "BBC Sport - Tennis"},
        {"url": "https://www.atptour.com/en/media/rss-feed/xml-feed", "verified": False, "notes": "Tennis - ATP World Tour"},
        {"url": "https://www.reddit.com/r/tennis/.rss", "verified": False, "notes": "Tennis News & Discussion"},
        {"url": "https://www.perfect-tennis.com/feed/", "verified": False, "notes": "peRFect Tennis"},
        {"url": "https://www.espn.com/espn/rss/tennis/news", "verified": False, "notes": "www.espn.com - TENNIS"},
        {"url": "https://feed.podbean.com/essentialtennis/feed.xml", "verified": False, "notes": "Essential Tennis Podcast - Instruction, Lessons, Tips"},
        {"url": "http://www.grandslamfantasytennis.com/feed/?x=1", "verified": False, "notes": "Grand Slam Fantasy Tennis"},
    ],
    "movies": [
        {"url": "https://feeds2.feedburner.com/slashfilm", "verified": False, "notes": "/Film"},
        {"url": "https://www.aintitcool.com/node/feed/", "verified": False, "notes": "Ain't It Cool News Feed"},
        {"url": "https://www.comingsoon.net/feed", "verified": False, "notes": "ComingSoon.net"},
        {"url": "https://deadline.com/feed/", "verified": False, "notes": "Deadline"},
        {"url": "https://filmschoolrejects.com/feed/", "verified": False, "notes": "Film School Rejects"},
        {"url": "https://www.firstshowing.net/feed/", "verified": False, "notes": "FirstShowing.net"},
        {"url": "https://www.indiewire.com/feed", "verified": False, "notes": "IndieWire"},
        {"url": "https://reddit.com/r/movies/.rss", "verified": False, "notes": "Movie News and Discussion"},
        {"url": "https://www.bleedingcool.com/movies/feed/", "verified": False, "notes": "Movies"},
        {"url": "https://film.avclub.com/rss", "verified": False, "notes": "The A.V. Club"},
        {"url": "https://variety.com/feed/", "verified": False, "notes": "Variety"},
    ],
    "television": [
        {"url": "https://www.bleedingcool.com/tv/feed/", "verified": False, "notes": "TV"},
        {"url": "https://www.tvfanatic.com/rss.xml", "verified": False, "notes": "TV Fanatic"},
        {"url": "https://tvline.com/feed/", "verified": False, "notes": "TVLine"},
        {"url": "https://reddit.com/r/television/.rss", "verified": False, "notes": "Television News and Discussion"},
        {"url": "https://tv.avclub.com/rss", "verified": False, "notes": "The A.V. Club"},
        {"url": "http://feeds.feedburner.com/thetvaddict/AXob", "verified": False, "notes": "the TV addict"},
    ],
    "music": [
        {"url": "https://www.billboard.com/articles/rss.xml", "verified": False, "notes": "Billboard"},
        {"url": "http://consequenceofsound.net/feed", "verified": False, "notes": "Consequence"},
        {"url": "https://edm.com/.rss/full/", "verified": False, "notes": "EDM.com"},
        {"url": "http://feeds.feedburner.com/metalinjection", "verified": False, "notes": "Metal Injection"},
        {"url": "https://www.musicbusinessworldwide.com/feed/", "verified": False, "notes": "Music Business Worldwide"},
        {"url": "http://pitchfork.com/rss/news", "verified": False, "notes": "RSS: News"},
        {"url": "https://www.youredm.com/feed", "verified": False, "notes": "Your EDM"},
        {"url": "http://songexploder.net/feed", "verified": False, "notes": "Song Exploder"},
    ],
    "fashion": [
        {"url": "https://www.elle.com/rss/fashion.xml/", "verified": False, "notes": "Fashion - ELLE"},
        {"url": "https://www.theguardian.com/fashion/rss", "verified": False, "notes": "Fashion - The Guardian"},
        {"url": "https://www.fashionlady.in/category/fashion/feed", "verified": False, "notes": "Fashion – Indian Fashion Blog"},
        {"url": "https://www.fashionbeans.com/rss-feed/?category=fashion", "verified": False, "notes": "FashionBeans Men's Fashion and Style Feed"},
        {"url": "https://fashionista.com/.rss/excerpt/", "verified": False, "notes": "Fashionista"},
        {"url": "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml", "verified": False, "notes": "NYT > Style"},
        {"url": "https://www.popsugar.com/fashion/feed", "verified": False, "notes": "POPSUGAR Fashion"},
        {"url": "https://www.refinery29.com/fashion/rss.xml", "verified": False, "notes": "Refinery29"},
        {"url": "https://www.yesstyle.com/blog/category/trend-and-style/feed/", "verified": False, "notes": "THE YESSTYLIST – Asian Fashion Blog"},
        {"url": "https://www.whowhatwear.com/rss", "verified": False, "notes": "Who What Wear"},
    ],
    "beauty": [
        {"url": "https://www.elle.com/rss/beauty.xml/", "verified": False, "notes": "Beauty - ELLE"},
        {"url": "https://fashionista.com/.rss/excerpt/beauty", "verified": False, "notes": "Beauty - Fashionista"},
        {"url": "https://www.fashionlady.in/category/beauty-tips/feed", "verified": False, "notes": "Beauty – Indian Fashion Blog"},
        {"url": "https://thebeautybrains.com/blog/feed/", "verified": False, "notes": "Blog – The Beauty Brains"},
        {"url": "https://www.wearedore.com/feed", "verified": False, "notes": "DORÉ"},
        {"url": "http://feeds.feedburner.com/frmheadtotoe", "verified": False, "notes": "From Head To Toe"},
        {"url": "https://feeds.feedburner.com/intothegloss/oqoU", "verified": False, "notes": "Into The Gloss"},
        {"url": "https://www.makeupandbeautyblog.com/feed/", "verified": False, "notes": "Makeup and Beauty Blog"},
        {"url": "https://www.popsugar.com/beauty/feed", "verified": False, "notes": "POPSUGAR Beauty"},
        {"url": "https://www.refinery29.com/beauty/rss.xml", "verified": False, "notes": "Refinery29"},
        {"url": "https://www.yesstyle.com/blog/category/the-beauty-blog/feed/", "verified": False, "notes": "THE YESSTYLIST – Asian Fashion Blog"},
        {"url": "https://thebeautylookbook.com/feed", "verified": False, "notes": "The Beauty Look Book"},
    ],
    "food": [
        {"url": "https://www.101cookbooks.com/feed", "verified": False, "notes": "101 Cookbooks"},
        {"url": "https://cnz.to/feed/", "verified": False, "notes": "Chocolate & Zucchini"},
        {"url": "https://www.davidlebovitz.com/feed/", "verified": False, "notes": "David Lebovitz"},
        {"url": "http://feeds.feedburner.com/food52-TheAandMBlog", "verified": False, "notes": "Food52"},
        {"url": "https://greenkitchenstories.com/feed/", "verified": False, "notes": "Green Kitchen Stories"},
        {"url": "https://www.howsweeteats.com/feed/", "verified": False, "notes": "How Sweet Eats"},
        {"url": "http://joythebaker.com/feed/", "verified": False, "notes": "Joy the Baker"},
        {"url": "https://www.thekitchn.com/main.rss", "verified": False, "notes": "Kitchn"},
        {"url": "https://www.loveandoliveoil.com/feed", "verified": False, "notes": "Love and Olive Oil"},
        {"url": "https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml", "verified": False, "notes": "NYT > Food"},
        {"url": "https://ohsheglows.com/feed/", "verified": False, "notes": "Oh She Glows"},
        {"url": "http://feeds.feedburner.com/seriouseats/recipes", "verified": False, "notes": "Serious Eats: Recipes"},
        {"url": "http://www.shutterbean.com/feed/", "verified": False, "notes": "Shutterbean"},
        {"url": "https://www.skinnytaste.com/feed/", "verified": False, "notes": "Skinnytaste"},
        {"url": "https://www.sproutedkitchen.com/home?format=rss", "verified": False, "notes": "Sprouted Kitchen"},
        {"url": "https://blog.williams-sonoma.com/feed/", "verified": False, "notes": "Williams-Sonoma Taste"},
        {"url": "http://feeds.feedburner.com/smittenkitchen", "verified": False, "notes": "smitten kitchen"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=bgfilms", "verified": False, "notes": "Babish Culinary Universe"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=BonAppetitDotCom", "verified": False, "notes": "Bon Appétit"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=LauraVitalesKitchen", "verified": False, "notes": "Laura in the Kitchen"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=SeriousEats", "verified": False, "notes": "Serious Eats"},
    ],
    "travel": [
        {"url": "https://www.atlasobscura.com/feeds/latest", "verified": False, "notes": "Atlas Obscura - Latest Articles and Places"},
        {"url": "https://www.livelifetravel.world/feed/", "verified": False, "notes": "Live Life Travel"},
        {"url": "https://www.lonelyplanet.com/news/feed/atom/", "verified": False, "notes": "Lonely Planet Travel News"},
        {"url": "https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml", "verified": False, "notes": "NYT > Travel"},
        {"url": "https://www.nomadicmatt.com/travel-blog/feed/", "verified": False, "notes": "Nomadic Matt's Travel Site"},
        {"url": "https://www.theguardian.com/uk/travel/rss", "verified": False, "notes": "Travel - The Guardian"},
    ],
    "cars": [
        {"url": "https://www.autoblog.com/rss.xml", "verified": False, "notes": "Autoblog"},
        {"url": "https://www.autocarindia.com/RSS/rss.ashx?type=News", "verified": False, "notes": "Autocar India - News"},
        {"url": "https://www.autocar.co.uk/rss", "verified": False, "notes": "Autocar RSS Feed"},
        {"url": "https://feeds.feedburner.com/BmwBlog", "verified": False, "notes": "BMW BLOG"},
        {"url": "https://www.bikeexif.com/feed", "verified": False, "notes": "Bike EXIF"},
        {"url": "https://www.carbodydesign.com/feed/", "verified": False, "notes": "Car Body Design"},
        {"url": "https://www.carscoops.com/feed/", "verified": False, "notes": "Carscoops"},
        {"url": "https://www.reddit.com/r/formula1/.rss", "verified": False, "notes": "Formula 1"},
        {"url": "https://jalopnik.com/rss", "verified": False, "notes": "Jalopnik"},
        {"url": "https://www.caranddriver.com/rss/all.xml/", "verified": False, "notes": "Latest Content - Car and Driver"},
        {"url": "https://petrolicious.com/feed", "verified": False, "notes": "Petrolicious"},
        {"url": "http://feeds.feedburner.com/autonews/AutomakerNews", "verified": False, "notes": "Section Page News - Automotive News"},
        {"url": "http://feeds.feedburner.com/speedhunters", "verified": False, "notes": "Speedhunters"},
        {"url": "https://www.thetruthaboutcars.com/feed/", "verified": False, "notes": "The Truth About Cars"},
        {"url": "https://bringatrailer.com/feed/", "verified": False, "notes": "Bring a Trailer"},
        {"url": "https://www.autocarindia.com/RSS/rss.ashx?type=all_bikes", "verified": False, "notes": "Autocar India - All Bike Reviews"},
        {"url": "https://www.autocarindia.com/RSS/rss.ashx?type=all_cars", "verified": False, "notes": "Autocar India - All Car Reviews"},
        {"url": "http://feeds.feedburner.com/autonews/EditorsPicks", "verified": False, "notes": "Section Page News - Automotive News"},
    ],
    "architecture": [
        {"url": "http://feeds.feedburner.com/archidose", "verified": False, "notes": "A Daily Dose of Architecture Books"},
        {"url": "http://feeds.feedburner.com/Archdaily", "verified": False, "notes": "ArchDaily"},
        {"url": "https://archinect.com/feed/1/news", "verified": False, "notes": "Archinect - News"},
        {"url": "https://www.architecturaldigest.com/feed/rss", "verified": False, "notes": "Architectural Digest"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=ArchitecturalDigest", "verified": False, "notes": "Architectural Digest"},
        {"url": "https://www.reddit.com/r/architecture/.rss", "verified": False, "notes": "Architecture"},
        {"url": "https://www.dezeen.com/architecture/feed/", "verified": False, "notes": "Architecture – Dezeen"},
        {"url": "https://www.contemporist.com/feed/", "verified": False, "notes": "CONTEMPORIST"},
        {"url": "https://inhabitat.com/architecture/feed/", "verified": False, "notes": "Comments on:"},
        {"url": "https://design-milk.com/category/architecture/feed/", "verified": False, "notes": "Design MilkArchitecture – Design Milk"},
        {"url": "https://architizer.wpengine.com/feed/", "verified": False, "notes": "Journal"},
        {"url": "https://www.youtube.com/feeds/videos.xml?user=livingbigtinyhouse", "verified": False, "notes": "Living Big In A Tiny House"},
        {"url": "https://archpaper.com/feed", "verified": False, "notes": "The Architect’s Newspaper"},
        {"url": "https://www.designboom.com/architecture/feed/", "verified": False, "notes": "architecture – designboom - architecture & design magazine"},
    ],
    "books": [
        {"url": "https://ayearofreadingtheworld.com/feed/", "verified": False, "notes": "A year of reading the world"},
        {"url": "https://aestasbookblog.com/feed/", "verified": False, "notes": "Aestas Book Blog"},
        {"url": "https://bookriot.com/feed/", "verified": False, "notes": "BOOK RIOT"},
        {"url": "https://www.kirkusreviews.com/feeds/rss/", "verified": False, "notes": "Kirkus Reviews"},
        {"url": "https://www.newinbooks.com/feed/", "verified": False, "notes": "Page Array – NewInBooks"},
        {"url": "https://reddit.com/r/books/.rss", "verified": False, "notes": "So many books, so little time"},
        {"url": "https://wokeread.home.blog/feed/", "verified": False, "notes": "Wokeread"},
    ],
    "interior_design": [
        {"url": "https://www.apartmenttherapy.com/design.rss", "verified": False, "notes": "Apartment Therapy- Saving the world, one room at a time"},
        {"url": "http://www.betterlivingthroughdesign.com/feed/", "verified": False, "notes": "Better Living Through Design"},
        {"url": "https://www.decor8blog.com/blog?format=rss", "verified": False, "notes": "Blog - decor8"},
        {"url": "http://feeds.feedburner.com/core77/blog", "verified": False, "notes": "Core77"},
        {"url": "https://design-milk.com/category/interior-design/feed/", "verified": False, "notes": "Design MilkInterior Design – Design Milk"},
        {"url": "http://feeds.feedburner.com/fubiz", "verified": False, "notes": "Fubiz Media"},
        {"url": "https://www.idealhome.co.uk/feed", "verified": False, "notes": "Ideal Home"},
        {"url": "https://inmyownstyle.com/feed", "verified": False, "notes": "In My Own Style"},
        {"url": "https://inhabitat.com/design/feed/", "verified": False, "notes": "Inhabitat - Green Design, Innovation, Architecture, Green Building"},
        {"url": "https://www.reddit.com/r/InteriorDesign/.rss", "verified": False, "notes": "Interior Design (Interior Architecture)"},
        {"url": "http://www.home-designing.com/feed", "verified": False, "notes": "Interior Design Ideas"},
        {"url": "https://www.interiordesign.net/rss/", "verified": False, "notes": "Interior Design Latest"},
        {"url": "https://www.dezeen.com/interiors/feed/", "verified": False, "notes": "Interiors – Dezeen"},
        {"url": "https://www.lizmarieblog.com/feed/", "verified": False, "notes": "Liz Marie Blog"},
        {"url": "https://thedesignfiles.net/feed/", "verified": False, "notes": "The Design Files - Australia's most popular design blog.The Design Files - Australia's most popular design blog."},
        {"url": "https://theinspiredroom.net/feed/", "verified": False, "notes": "The Inspired Room"},
        {"url": "http://feeds.feedburner.com/blogspot/ZBcZ", "verified": False, "notes": "Thrifty Decor Chick"},
        {"url": "https://www.trendir.com/feed/", "verified": False, "notes": "Trendir"},
        {"url": "http://feeds.feedburner.com/yankodesign", "verified": False, "notes": "Yanko Design"},
        {"url": "https://www.yatzer.com/rss.xml", "verified": False, "notes": "Yatzer RSS Feed"},
        {"url": "https://www.younghouselove.com/feed/", "verified": False, "notes": "Young House Love"},
        {"url": "https://www.decoist.com/feed/", "verified": False, "notes": "decoist"},
        {"url": "https://www.designboom.com/design/feed", "verified": False, "notes": "design – designboom - architecture & design magazine"},
        {"url": "https://www.sfgirlbybay.com/feed/", "verified": False, "notes": "sfgirlbybay"},
    ],
    "diy": [
        {"url": "https://abeautifulmess.com/feed", "verified": False, "notes": "A Beautiful Mess"},
        {"url": "https://www.apartmenttherapy.com/projects.rss", "verified": False, "notes": "Apartment Therapy- Saving the world, one room at a time"},
        {"url": "https://hackaday.com/blog/feed/", "verified": False, "notes": "Blog – Hackaday"},
        {"url": "https://centsationalstyle.com/feed/", "verified": False, "notes": "Centsational Style"},
        {"url": "https://www.doityourself.com/feed", "verified": False, "notes": "Doityourself.com"},
        {"url": "https://blog.etsy.com/en/feed/", "verified": False, "notes": "Etsy Journal"},
        {"url": "https://www.howtogeek.com/feed/", "verified": False, "notes": "How-To Geek"},
        {"url": "https://www.ikeahackers.net/feed", "verified": False, "notes": "IKEA Hackers"},
        {"url": "https://www.makeuseof.com/feed/", "verified": False, "notes": "MUO - Feed"},
        {"url": "http://ohhappyday.com/feed/", "verified": False, "notes": "Oh Happy Day!"},
        {"url": "https://www.wonderhowto.com/rss.xml", "verified": False, "notes": "WonderHowTo"},
    ],
    "funny": [
        {"url": "https://awkwardfamilyphotos.com/feed/", "verified": False, "notes": "AwkwardFamilyPhotos.com"},
        {"url": "http://feeds.feedburner.com/CrackedRSS", "verified": False, "notes": "Cracked: All Posts"},
        {"url": "http://feeds.feedburner.com/Explosm", "verified": False, "notes": "Explosm.net"},
        {"url": "http://feeds.feedburner.com/failblog", "verified": False, "notes": "FAIL Blog"},
        {"url": "http://feeds.feedburner.com/icanhascheezburger", "verified": False, "notes": "I Can Has Cheezburger?"},
        {"url": "http://phdcomics.com/gradfeed.php", "verified": False, "notes": "PHD Comics"},
        {"url": "https://www.penny-arcade.com/feed", "verified": False, "notes": "Penny Arcade"},
        {"url": "https://postsecret.com/feed/?alt=rss", "verified": False, "notes": "PostSecret"},
        {"url": "https://www.smbc-comics.com/comic/rss", "verified": False, "notes": "Saturday Morning Breakfast Cereal"},
        {"url": "https://thebloggess.com/feed/", "verified": False, "notes": "The Bloggess"},
        {"url": "http://syndication.thedailywtf.com/TheDailyWtf", "verified": False, "notes": "The Daily WTF"},
        {"url": "http://feeds.feedburner.com/oatmealfeed", "verified": False, "notes": "The Oatmeal - Comics by Matthew Inman"},
        {"url": "https://www.theonion.com/rss", "verified": False, "notes": "The Onion"},
        {"url": "https://xkcd.com/rss.xml", "verified": False, "notes": "xkcd.com"},
    ],
    "history": [
        {"url": "https://feeds.megaphone.fm/ESP5765452710", "verified": False, "notes": "30 For 30 Podcasts"},
        {"url": "https://americanhistory.si.edu/blog/feed", "verified": False, "notes": "Blog Feed"},
        {"url": "https://feeds.feedburner.com/dancarlin/history?format=xml", "verified": False, "notes": "Dan Carlin's Hardcore History"},
        {"url": "https://www.historyisnowmagazine.com/blog?format=RSS", "verified": False, "notes": "History in 28-minutes"},
        {"url": "http://www.historynet.com/feed", "verified": False, "notes": "HistoryNet"},
        {"url": "https://feeds.megaphone.fm/lore", "verified": False, "notes": "Lore"},
        {"url": "https://feeds.megaphone.fm/revisionisthistory", "verified": False, "notes": "Revisionist History"},
        {"url": "https://www.thehistoryreader.com/feed/", "verified": False, "notes": "The History Reader"},
        {"url": "https://feeds.npr.org/510333/podcast.xml", "verified": False, "notes": "Throughline"},
        {"url": "https://feeds.megaphone.fm/YMRT7068253588", "verified": False, "notes": "You Must Remember This"},
        {"url": "http://feeds.thememorypalace.us/thememorypalace", "verified": False, "notes": "the memory palace"},
    ],
    "personal_finance": [
        {"url": "https://affordanything.com/feed/", "verified": False, "notes": "Afford Anything"},
        {"url": "https://studentloanhero.com/blog/feed", "verified": False, "notes": "Blog – Student Loan Hero"},
        {"url": "https://feeds2.feedburner.com/budgetsaresexy", "verified": False, "notes": "Budgets Are Sexy"},
        {"url": "https://www.financialsamurai.com/feed/", "verified": False, "notes": "Financial Samurai"},
        {"url": "https://feeds.feedburner.com/Frugalwoods", "verified": False, "notes": "Frugalwoods"},
        {"url": "https://www.getrichslowly.org/feed/", "verified": False, "notes": "Get Rich Slowly"},
        {"url": "https://www.goodfinancialcents.com/feed/", "verified": False, "notes": "Good Financial Cents®"},
        {"url": "https://www.iwillteachyoutoberich.com/feed/", "verified": False, "notes": "I Will Teach You To Be Rich"},
        {"url": "https://www.learntotradethemarket.com/feed", "verified": False, "notes": "Learn To Trade The Market"},
        {"url": "https://www.makingsenseofcents.com/feed", "verified": False, "notes": "Making Sense Of Cents"},
        {"url": "https://millennialmoney.com/feed/", "verified": False, "notes": "Millennial Money"},
        {"url": "https://blog.mint.com/feed/", "verified": False, "notes": "MintLife Blog"},
        {"url": "https://www.moneycrashers.com/feed/", "verified": False, "notes": "Money Crashers"},
        {"url": "https://moneysavingmom.com/feed/", "verified": False, "notes": "Money Saving Mom®"},
        {"url": "https://www.moneyunder30.com/feed", "verified": False, "notes": "Money Under 30"},
        {"url": "http://feeds.feedburner.com/MoneyNing", "verified": False, "notes": "MoneyNing"},
        {"url": "https://mywifequitherjob.com/feed/", "verified": False, "notes": "MyWifeQuitHerJob.com"},
        {"url": "http://feeds.feedblitz.com/kitcesnerdseyeview&x=1", "verified": False, "notes": "Nerd's Eye View - Kitces.com"},
        {"url": "https://www.nerdwallet.com/blog/feed/", "verified": False, "notes": "NerdWallet"},
        {"url": "https://obliviousinvestor.com/feed/", "verified": False, "notes": "Oblivious Investor"},
        {"url": "https://reddit.com/r/personalfinance/.rss", "verified": False, "notes": "Personal Finance"},
        {"url": "https://www.savingadvice.com/feed/", "verified": False, "notes": "SavingAdvice.com Blog"},
        {"url": "https://www.sidehustlenation.com/feed", "verified": False, "notes": "Side Hustle Nation"},
        {"url": "https://thecollegeinvestor.com/feed/", "verified": False, "notes": "The College Investor"},
        {"url": "https://www.doughroller.net/feed/", "verified": False, "notes": "The Dough Roller"},
        {"url": "https://www.thepennyhoarder.com/feed/", "verified": False, "notes": "The Penny Hoarder"},
        {"url": "https://wellkeptwallet.com/feed/", "verified": False, "notes": "Well Kept Wallet"},
        {"url": "http://feeds.killeraces.com/wisebread", "verified": False, "notes": "Wise Bread"},
    ],
    "photography": [
        {"url": "https://iso.500px.com/feed/", "verified": False, "notes": "500px"},
        {"url": "https://500px.com/editors.rss", "verified": False, "notes": "500px:"},
        {"url": "https://www.bostonglobe.com/rss/bigpicture", "verified": False, "notes": "Big Picture"},
        {"url": "https://www.canonrumors.com/feed/", "verified": False, "notes": "Canon Rumors – Your best source for Canon rumors, leaks and gossip"},
        {"url": "https://feeds.feedburner.com/DigitalPhotographySchool", "verified": False, "notes": "Digital Photography School"},
        {"url": "https://www.lightstalking.com/feed/", "verified": False, "notes": "Light Stalking"},
        {"url": "https://lightroomkillertips.com/feed/", "verified": False, "notes": "Lightroom Killer Tips"},
        {"url": "http://feeds.feedburner.com/OneBigPhoto", "verified": False, "notes": "One Big Photo"},
        {"url": "https://petapixel.com/feed/", "verified": False, "notes": "PetaPixel"},
        {"url": "http://feeds.feedburner.com/blogspot/WOBq", "verified": False, "notes": "Strobist"},
        {"url": "https://stuckincustoms.com/feed/", "verified": False, "notes": "Stuck in Customs"},
        {"url": "https://feeds.feedburner.com/TheSartorialist", "verified": False, "notes": "The Sartorialist"},
    ],
    "science": [
        {"url": "http://rss.sciam.com/sciam/60secsciencepodcast", "verified": False, "notes": "60-Second Science"},
        {"url": "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", "verified": False, "notes": "BBC News - Science & Environment"},
        {"url": "https://podcasts.files.bbci.co.uk/p002w557.rss", "verified": False, "notes": "Discovery"},
        {"url": "https://flowingdata.com/feed", "verified": False, "notes": "FlowingData"},
        {"url": "https://www.omnycontent.com/d/playlist/aaea4e69-af51-495e-afc9-a9760146922b/2a195077-f014-41d2-8313-ab190186b4c2/277bcd5c-0a05-4c14-8ba6-ab190186b4d5/podcast.rss", "verified": False, "notes": "Gastropod"},
        {"url": "https://gizmodo.com/tag/science/rss", "verified": False, "notes": "Gizmodo"},
        {"url": "https://feeds.npr.org/510308/podcast.xml", "verified": False, "notes": "Hidden Brain"},
        {"url": "https://feeds.npr.org/510307/podcast.xml", "verified": False, "notes": "Invisibilia"},
        {"url": "https://www.sciencedaily.com/rss/all.xml", "verified": False, "notes": "Latest Science News -- ScienceDaily"},
        {"url": "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml", "verified": False, "notes": "NYT > Science"},
        {"url": "https://www.nature.com/nature.rss", "verified": False, "notes": "Nature"},
        {"url": "https://phys.org/rss-feed/", "verified": False, "notes": "Phys.org - latest science and technology news stories"},
        {"url": "https://probablyscience.libsyn.com/rss", "verified": False, "notes": "Probably Science"},
        {"url": "http://feeds.wnyc.org/radiolab", "verified": False, "notes": "Radiolab"},
        {"url": "https://reddit.com/r/science/.rss", "verified": False, "notes": "Reddit Science"},
        {"url": "https://feeds.simplecast.com/y1LF_sn2", "verified": False, "notes": "Sawbones: A Marital Tour of Misguided Medicine"},
        {"url": "https://www.wired.com/feed/category/science/latest/rss", "verified": False, "notes": "Science Latest"},
        {"url": "http://feeds.gimletmedia.com/ScienceVs", "verified": False, "notes": "Science Vs"},
        {"url": "https://sciencebasedmedicine.org/feed/", "verified": False, "notes": "Science-Based Medicine"},
        {"url": "http://rss.sciam.com/ScientificAmerican-Global", "verified": False, "notes": "Scientific American Content: Global"},
        {"url": "https://shirtloadsofscience.libsyn.com/rss", "verified": False, "notes": "Shirtloads of Science"},
        {"url": "https://pa.tedcdn.com/feeds/talks.rss", "verified": False, "notes": "TED Talks Daily (SD video)"},
        {"url": "https://podcasts.files.bbci.co.uk/b00snr0w.rss", "verified": False, "notes": "The Infinite Monkey Cage"},
        {"url": "http://www.twis.org/feed/", "verified": False, "notes": "This Week in Science – The Kickass Science Podcast"},
    ],
}
